#!/usr/bin/env ruby
require 'pathname'
require 'fileutils'
# include FileUtils

# path to your application root.
APP_ROOT = Pathname.new File.expand_path('..', __dir__)

def system!(*args)
  system(*args) || abort("\n== Command #{args} failed ==")
end

chdir APP_ROOT do
  # This script is a starting point to setup your application.
  # Add necessary setup steps to this file.

  Rails.logger.info '== Installing dependencies =='
  system! 'gem install bundler --conservative'
  system('bundle check') || system!('bundle install')

  # Rails.logger.info "\n== Copying sample files =="
  # unless File.exist?('config/database.yml')
  #   cp 'config/database.yml.sample', 'config/database.yml'
  # end

  Rails.logger.info "\n== Preparing database =="
  system! 'bin/rails db:setup'

  Rails.logger.info "\n== Removing old logs and tempfiles =="
  system! 'bin/rails log:clear tmp:clear'

  Rails.logger.info "\n== Restarting application server =="
  system! 'bin/rails restart'
end
